services:
  digao-cloud-gaming-web:
    build:
      context: ../../clients/web/cloud-gaming
    container_name: digao-cloud-gaming-web
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - npm_dev

  oauth2-proxy-cloud-gaming:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.7.1
    container_name: oauth2-proxy-cloud-gaming-dev
    restart: unless-stopped
    env_file:
      - ./host/oauth2-proxy.env
    networks:
      - npm_dev

networks:
  npm_dev:
    external: true
